name: hemocycle
description: "The HemoCycle App Fornt-end."

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.10.5
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/avatar.png
    - assets/images/camera.png
    - assets/images/heart.png
    - assets/images/the_girl.png
    - assets/images/the_eye.jpg

  uses-material-design: true

